#!/usr/bin/env ruby
# frozen_string_literal: true
#/ Usage: install.sh
#/ Provides a lite installation, used primarily by GitHub Codespaces.

require 'fileutils'

# Install Git config
{
  "git/gitconfig-core.symlink" => ".gitconfig",
  "git/gitignore.symlink" => ".gitignore",
}.each do |src, dst|
  begin
    FileUtils.ln_s(File.expand_path(src, __dir__), File.expand_path(dst, ENV["HOME"]))
    puts "#{dst} symlinked"
  rescue Errno::EEXIST
    puts "#{dst} already exists, skipping"
  end
end

# Add dotfiles/bin to PATH
File.open(File.expand_path(".bashrc", ENV["HOME"]), "a") do |f|
  f.puts
  f.puts "# Add @parkr's dotfiles bin dir to PATH"
  f.puts "export PATH=$PATH:\"#{File.expand_path("bin", __dir__)}\""
end
