all:
	@true

ibm-plex-mono:
	wget https://github.com/IBM/type/archive/master.tar.gz -O ibm-plex-mono.tar.gz
	tar -xzvf ibm-plex-mono.tar.gz
	rm ibm-plex-mono.tar.gz
	open type-master/fonts/Mono/desktop/mac/*.otf
#	rm -r type-master
